/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/sanity/schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type PortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Resource = {
  _type: "resource";
  type?: "article" | "code" | "download" | "link" | "tool";
  title?: string;
  description?: string;
  url?: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon?:
    | "code"
    | "compass"
    | "gauge"
    | "layers"
    | "lightbulb"
    | "play"
    | "puzzle"
    | "rocket"
    | "shield"
    | "sparkles"
    | "target"
    | "workflow";
  title?: string;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type CourseModule = {
  _type: "courseModule";
  title?: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  videoUrl?: string;
  thumbnail?: ImageWithAlt;
  duration?: number;
  freePreview?: boolean;
  studentCount?: number;
  notes?: PortableText;
  keyPoints?: Array<string>;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  coverImage?: ImageWithAlt;
  level?: "beginner" | "intermediate" | "advanced";
  price?: number;
  popular?: boolean;
  studentCount?: number;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  instructor?: InstructorReference;
  category?: CategoryReference;
  modules?: Array<
    {
      _key: string;
    } & CourseModule
  >;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: ImageWithAlt;
  expertise?: Array<string>;
  bio?: PortableText;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ImageWithAlt
  | PortableText
  | Resource
  | LearningOutcome
  | LessonReference
  | CourseModule
  | Lesson
  | Slug
  | InstructorReference
  | CategoryReference
  | Course
  | Category
  | Instructor
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/sanity/queries/categories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id, title, "slug": slug.current, description,    "courseCount": count(*[_type == "course" && category._ref == ^._id])  }
export type ALL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  courseCount: number;
}>;

// Source: ../web/sanity/queries/categories.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {    _id, title, "slug": slug.current, description,    "courses": *[_type == "course" && category._ref == ^._id] | order(title asc) {      _id, title, "slug": slug.current, summary,      coverImage {alt, asset->{_id, url, metadata {lqip, dimensions}}},      level, price, popular, studentCount,      "moduleCount": count(modules),      "lessonCount": count(modules[].lessons[]),      "duration": math::sum(modules[].lessons[]->duration),      instructor->{_id, name, "slug": slug.current}    }  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    summary: string | null;
    coverImage: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
    level: "advanced" | "beginner" | "intermediate" | null;
    price: number | null;
    popular: boolean | null;
    studentCount: number | null;
    moduleCount: number | null;
    lessonCount: number | null;
    duration: number | null;
    instructor: {
      _id: string;
      name: string | null;
      slug: string | null;
    } | null;
  }>;
} | null;

// Source: ../web/sanity/queries/courses.ts
// Variable: ALL_COURSES_QUERY
// Query: *[_type == "course"] | order(title asc) {    _id, title, "slug": slug.current, summary,    coverImage {alt, asset->{_id, url, metadata {lqip, dimensions}}},    level, price, popular, studentCount,    "moduleCount": count(modules),    "lessonCount": count(modules[].lessons[]),    "duration": math::sum(modules[].lessons[]->duration),    instructor->{_id, name, "slug": slug.current},    category->{_id, title, "slug": slug.current}  }
export type ALL_COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  coverImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  moduleCount: number | null;
  lessonCount: number | null;
  duration: number | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: string | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
}>;

// Source: ../web/sanity/queries/courses.ts
// Variable: POPULAR_COURSES_QUERY
// Query: *[_type == "course" && popular == true] | order(studentCount desc, title asc) {    _id, title, "slug": slug.current, summary,    coverImage {alt, asset->{_id, url, metadata {lqip, dimensions}}},    level, price, popular, studentCount,    "moduleCount": count(modules),    "lessonCount": count(modules[].lessons[]),    "duration": math::sum(modules[].lessons[]->duration),    instructor->{_id, name, "slug": slug.current},    category->{_id, title, "slug": slug.current}  }
export type POPULAR_COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  coverImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  popular: true;
  studentCount: number | null;
  moduleCount: number | null;
  lessonCount: number | null;
  duration: number | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: string | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
}>;

// Source: ../web/sanity/queries/courses.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {    _id, title, "slug": slug.current, summary,    coverImage {alt, asset->{_id, url, metadata {lqip, dimensions}}},    level, price, popular, studentCount,    learningOutcomes[]{_key, icon, title, description},    instructor->{      _id, name, "slug": slug.current,      photo {alt, asset->{_id, url, metadata {lqip, dimensions}}},      expertise    },    category->{_id, title, "slug": slug.current, description},    modules[]{      _key, title, summary,      lessons[]->{        _id, title, "slug": slug.current,        thumbnail {alt, asset->{_id, url, metadata {lqip, dimensions}}},        duration, freePreview, studentCount, keyPoints      }    }  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  coverImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  learningOutcomes: Array<{
    _key: string;
    icon:
      | "code"
      | "compass"
      | "gauge"
      | "layers"
      | "lightbulb"
      | "play"
      | "puzzle"
      | "rocket"
      | "shield"
      | "sparkles"
      | "target"
      | "workflow"
      | null;
    title: string | null;
    description: string | null;
  }> | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: string | null;
    photo: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
    expertise: Array<string> | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
    description: string | null;
  } | null;
  modules: Array<{
    _key: string;
    title: string | null;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string | null;
      slug: string | null;
      thumbnail: {
        alt: string | null;
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
      } | null;
      duration: number | null;
      freePreview: boolean | null;
      studentCount: number | null;
      keyPoints: Array<string> | null;
    }> | null;
  }> | null;
} | null;

// Source: ../web/sanity/queries/instructors.ts
// Variable: ALL_INSTRUCTORS_QUERY
// Query: *[_type == "instructor"] | order(name asc) {    _id, name, "slug": slug.current,    photo {alt, asset->{_id, url, metadata {lqip, dimensions}}},    expertise,    "courseCount": count(*[_type == "course" && instructor._ref == ^._id])  }
export type ALL_INSTRUCTORS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  photo: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  expertise: Array<string> | null;
  courseCount: number;
}>;

// Source: ../web/sanity/queries/instructors.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {    _id, name, "slug": slug.current,    photo {alt, asset->{_id, url, metadata {lqip, dimensions}}},    expertise, bio[]{...},    "courses": *[_type == "course" && instructor._ref == ^._id] | order(title asc) {      _id, title, "slug": slug.current, summary,      coverImage {alt, asset->{_id, url, metadata {lqip, dimensions}}},      level, price, popular, studentCount,      "moduleCount": count(modules),      "lessonCount": count(modules[].lessons[]),      "duration": math::sum(modules[].lessons[]->duration),      category->{_id, title, "slug": slug.current}    }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  photo: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  expertise: Array<string> | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    summary: string | null;
    coverImage: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
    level: "advanced" | "beginner" | "intermediate" | null;
    price: number | null;
    popular: boolean | null;
    studentCount: number | null;
    moduleCount: number | null;
    lessonCount: number | null;
    duration: number | null;
    category: {
      _id: string;
      title: string | null;
      slug: string | null;
    } | null;
  }>;
} | null;

// Source: ../web/sanity/queries/lessons.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0] {    _id, title, "slug": slug.current, videoUrl,    thumbnail {alt, asset->{_id, url, metadata {lqip, dimensions}}},    duration, freePreview, studentCount,    notes[]{...}, keyPoints, proTip,    resources[]{_key, type, title, description, url},    "course": *[_type == "course" && references(^._id)][0] {      _id, title, "slug": slug.current,      coverImage {alt, asset->{_id, url}},      instructor->{        _id, name, "slug": slug.current,        photo {alt, asset->{_id, url}}, expertise      },      modules[]{_key, title, summary, "lessonIds": lessons[]._ref}    }  }
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  videoUrl: string | null;
  thumbnail: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  duration: number | null;
  freePreview: boolean | null;
  studentCount: number | null;
  notes: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type: "article" | "code" | "download" | "link" | "tool" | null;
    title: string | null;
    description: string | null;
    url: string | null;
  }> | null;
  course: {
    _id: string;
    title: string | null;
    slug: string | null;
    coverImage: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
    instructor: {
      _id: string;
      name: string | null;
      slug: string | null;
      photo: {
        alt: string | null;
        asset: {
          _id: string;
          url: string | null;
        } | null;
      } | null;
      expertise: Array<string> | null;
    } | null;
    modules: Array<{
      _key: string;
      title: string | null;
      summary: string | null;
      lessonIds: Array<string> | null;
    }> | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "category"] | order(title asc) {\n    _id, title, "slug": slug.current, description,\n    "courseCount": count(*[_type == "course" && category._ref == ^._id])\n  }\n': ALL_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug][0] {\n    _id, title, "slug": slug.current, description,\n    "courses": *[_type == "course" && category._ref == ^._id] | order(title asc) {\n      _id, title, "slug": slug.current, summary,\n      coverImage {alt, asset->{_id, url, metadata {lqip, dimensions}}},\n      level, price, popular, studentCount,\n      "moduleCount": count(modules),\n      "lessonCount": count(modules[].lessons[]),\n      "duration": math::sum(modules[].lessons[]->duration),\n      instructor->{_id, name, "slug": slug.current}\n    }\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "course"] | order(title asc) {\n    _id, title, "slug": slug.current, summary,\n    coverImage {alt, asset->{_id, url, metadata {lqip, dimensions}}},\n    level, price, popular, studentCount,\n    "moduleCount": count(modules),\n    "lessonCount": count(modules[].lessons[]),\n    "duration": math::sum(modules[].lessons[]->duration),\n    instructor->{_id, name, "slug": slug.current},\n    category->{_id, title, "slug": slug.current}\n  }\n': ALL_COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && popular == true] | order(studentCount desc, title asc) {\n    _id, title, "slug": slug.current, summary,\n    coverImage {alt, asset->{_id, url, metadata {lqip, dimensions}}},\n    level, price, popular, studentCount,\n    "moduleCount": count(modules),\n    "lessonCount": count(modules[].lessons[]),\n    "duration": math::sum(modules[].lessons[]->duration),\n    instructor->{_id, name, "slug": slug.current},\n    category->{_id, title, "slug": slug.current}\n  }\n': POPULAR_COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0] {\n    _id, title, "slug": slug.current, summary,\n    coverImage {alt, asset->{_id, url, metadata {lqip, dimensions}}},\n    level, price, popular, studentCount,\n    learningOutcomes[]{_key, icon, title, description},\n    instructor->{\n      _id, name, "slug": slug.current,\n      photo {alt, asset->{_id, url, metadata {lqip, dimensions}}},\n      expertise\n    },\n    category->{_id, title, "slug": slug.current, description},\n    modules[]{\n      _key, title, summary,\n      lessons[]->{\n        _id, title, "slug": slug.current,\n        thumbnail {alt, asset->{_id, url, metadata {lqip, dimensions}}},\n        duration, freePreview, studentCount, keyPoints\n      }\n    }\n  }\n': COURSE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "instructor"] | order(name asc) {\n    _id, name, "slug": slug.current,\n    photo {alt, asset->{_id, url, metadata {lqip, dimensions}}},\n    expertise,\n    "courseCount": count(*[_type == "course" && instructor._ref == ^._id])\n  }\n': ALL_INSTRUCTORS_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0] {\n    _id, name, "slug": slug.current,\n    photo {alt, asset->{_id, url, metadata {lqip, dimensions}}},\n    expertise, bio[]{...},\n    "courses": *[_type == "course" && instructor._ref == ^._id] | order(title asc) {\n      _id, title, "slug": slug.current, summary,\n      coverImage {alt, asset->{_id, url, metadata {lqip, dimensions}}},\n      level, price, popular, studentCount,\n      "moduleCount": count(modules),\n      "lessonCount": count(modules[].lessons[]),\n      "duration": math::sum(modules[].lessons[]->duration),\n      category->{_id, title, "slug": slug.current}\n    }\n  }\n': INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $slug][0] {\n    _id, title, "slug": slug.current, videoUrl,\n    thumbnail {alt, asset->{_id, url, metadata {lqip, dimensions}}},\n    duration, freePreview, studentCount,\n    notes[]{...}, keyPoints, proTip,\n    resources[]{_key, type, title, description, url},\n    "course": *[_type == "course" && references(^._id)][0] {\n      _id, title, "slug": slug.current,\n      coverImage {alt, asset->{_id, url}},\n      instructor->{\n        _id, name, "slug": slug.current,\n        photo {alt, asset->{_id, url}}, expertise\n      },\n      modules[]{_key, title, summary, "lessonIds": lessons[]._ref}\n    }\n  }\n': LESSON_BY_SLUG_QUERY_RESULT;
  }
}
